// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment("WEB_API_KEY"),
    appId: String.fromEnvironment("WEB_API_ID"),
    messagingSenderId: '161949604535',
    projectId: 'sem-nome-ainda-a569c',
    authDomain: 'sem-nome-ainda-a569c.firebaseapp.com',
    storageBucket: 'sem-nome-ainda-a569c.firebasestorage.app',
    measurementId: 'G-MS5P5XV6TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment("ANDROID_API_KEY"),
    appId: String.fromEnvironment("ANDROID_API_ID"),
    messagingSenderId: '161949604535',
    projectId: 'sem-nome-ainda-a569c',
    storageBucket: 'sem-nome-ainda-a569c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment("IOS_API_KEY"),
    appId: String.fromEnvironment("IOS_API_ID"),
    messagingSenderId: '161949604535',
    projectId: 'sem-nome-ainda-a569c',
    storageBucket: 'sem-nome-ainda-a569c.firebasestorage.app',
    iosClientId:
        '161949604535-qr5mb9ljivbhe0onidhe4k4cqm2vceos.apps.googleusercontent.com',
    iosBundleId: 'com.example.semNomeAinda',
  );
}
