// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdAIMOnCiVOuqzRcEUPayhphDmuLTy4U',
    appId: '1:161949604535:web:e2b63bd9ee44fda231cb32',
    messagingSenderId: '161949604535',
    projectId: 'sem-nome-ainda-a569c',
    authDomain: 'sem-nome-ainda-a569c.firebaseapp.com',
    storageBucket: 'sem-nome-ainda-a569c.firebasestorage.app',
    measurementId: 'G-MS5P5XV6TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi6LHgEopKdMNGlgZTfKS-nzcTvKL1Ylc',
    appId: '1:161949604535:android:04725b6e4c0465df31cb32',
    messagingSenderId: '161949604535',
    projectId: 'sem-nome-ainda-a569c',
    storageBucket: 'sem-nome-ainda-a569c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6pbm3HNpTVmybfuVTN5uQ0biGhtqHSrk',
    appId: '1:161949604535:ios:d9d5f5f932f3c5b531cb32',
    messagingSenderId: '161949604535',
    projectId: 'sem-nome-ainda-a569c',
    storageBucket: 'sem-nome-ainda-a569c.firebasestorage.app',
    iosClientId:
        '161949604535-qr5mb9ljivbhe0onidhe4k4cqm2vceos.apps.googleusercontent.com',
    iosBundleId: 'com.example.semNomeAinda',
  );
}
